# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
    - name: "People"
      url: "people/"
      weight: 30

    - name: "Research"
      url: "research/"
      weight: 40

    - name: Blog
      url: "post/"
      weight: 50

    - name: Publications
      url: "publication/"
      weight: 60

    - name: Participate
      url: "research#participate"
      weight: 65

    - name: "Join us"
      url: "jobs/"
      weight: 70
      identifier: jobs
    - name: Postdoc
      PageRef: jobs/postdoc.md
      weight: 10
      parent: jobs
    - name: PhD
      PageRef: jobs/phd.md
      weight: 20
      parent: jobs
    - name: Research Assistant
      PageRef: jobs/assistant.md
      weight: 30
      parent: jobs
    - name: Internship
      PageRef: jobs/intern.md
      weight: 40
      parent: jobs
    - name: Research Projects
      PageRef: jobs/projects.md
      weight: 50
      parent: jobs
    - name: Advice for Students
      PageRef: jobs/advice.md
      weight: 60
      parent: jobs
    # - name: Companion
    #   PageRef: jobs/companion.md
    #   weight: 50
    #   parent: jobs

    - name: "Contact"
      url: "#11_contact"
      weight: 80

    - name: '<i class="fab fa-github"; font-size: 1rem; line-height: 1.25"></i>'
      url: "https://github.com/RealityBending"
      weight: 90

    # - name: Home
    #   url: "#about"
    #   weight: 10
    # - name: Posts
    #   url: "#posts"
    #   weight: 20
    # - name: Projects
    #   url: "#projects"
    #   weight: 30
    # - name: Talks
    #   url: "#talks"
    #   weight: 40
    # - name: Publications
    #   url: "#featured"
    #   weight: 50
    # - name: Contact
    #   url: "#contact"
    #   weight: 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
